Сверстан макет по проекту MovieQuiz, разработана логика работы прилож…
vagamagajaga/MovieQuiz-ios pull request #2
Opened 2022-10-23 17:49 UTC by vagamagajaga

Сверстан макет по проекту MovieQuiz, разработана логика работы приложения.

2022-10-23 18:19 UTC, ABashkirova requested changes
1. Исправьте runtime ошибку с доступом к цветам. (то как назван и закончен файл, отличается от того имени, что вы используете в иницилизацторе UIColor) 
 <img width="228" alt="Screenshot 2022-10-23 at 22 15 06" src="https://user-images.githubusercontent.com/20269264/197408936-1e6447d5-f81c-4f35-aa70-c3481132e4bb.png"><img width="228" alt="Screenshot 2022-10-23 at 22 15 15" src="https://user-images.githubusercontent.com/20269264/197408942-71caeb59-ff66-4921-8df5-14953b5b70b4.png">

2. Нужно привести к макету экран: правильно добавить шрифты, настроить фон, исправить ворниги на storyboard. 
<img width="604" alt="Screenshot 2022-10-23 at 22 13 50" src="https://user-images.githubusercontent.com/20269264/197408849-3414399d-0d0f-4baf-afc4-364e0bfcbb5f.png">
3. Проверить модификаторы доступа у функции и переменных

2022-10-23 18:19 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var movieCount: UILabel!
Не забывайте добавлять модификатор приватности

2022-10-23 18:19 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    }
Лишние пустые строки принято убирать, а между логическими блоками оставляют только одну строку
```suggestion
    }
    
```

2022-10-23 18:19 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        movieImage.layer.cornerRadius = 20
masksToBounds и cornerRadius можно настроить единожды

2022-10-24 17:41 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var movieCount: UILabel!
Оставляю комментарий относительно ворнинга в сториборд: мне пришлось применить констрейты к главному вертикальному стэку, чтобы разрешить ворнинги, хоть в уроке констрейты рассчитаны к родительскому вью.

2022-10-24 20:30 UTC, ABashkirova requested changes
Привет!

- Цвет фона должен быть ypBlack
- Текст все еще не помещается: недостаточно места. Нужен нижний констрейнт у главного стека выставить нулевым от safe area. Количество строк лучше не ограничивать 2-мя. И попробуйте пойти на компромис и верхние констрейнты по 13 у вопроса уменьшить  до 5. 
- 
<img width="238" alt="Screenshot 2022-10-25 at 00 22 54" src="https://user-images.githubusercontent.com/20269264/197621665-dd756265-4e08-47cb-ab2c-00a7ed23155a.png">


- Шрифты все еще не отображаются. Нужно выставить таргет MovieQuiz, чтобы они подтянулись. 
<img width="254" alt="Screenshot 2022-10-25 at 00 26 55" src="https://user-images.githubusercontent.com/20269264/197622343-a3d91caa-aae7-47a2-96d9-03578d85c584.png">
- Изменения с цветами не применились. Посмотрите как выглядят файлы в гите. Код все еще крашится.
<img width="200" alt="Screenshot 2022-10-25 at 00 28 27" src="https://user-images.githubusercontent.com/20269264/197622560-cb6db575-9bfe-4ee1-bb6d-ea86484e331a.png">

2022-10-24 20:42 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var movieCount: UILabel!
Александра, я так долго мучился с этим констрейном, приняв за истину данные в курсе и в макете значения, а сейчас вы мне пишите, чтобы я сделал их помягче. Объясните, пожалуйста, эти ограничения только у меня вызывают проблемы с приложением, или все меняют констрейнт, а в курсе все также указаны неподходящие значения?

2022-10-25 08:33 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var movieCount: UILabel!
Привет, Ваган, на самом деле я сама в замешательстве, почему простого правильного констрейнта по низу экрана было недостаточно. Возможно повлияли дополнительные настройки лейбла, надо сравнивать.

Встречаются работы где 1к1 констрейнты этого контейнера совпадают с макетом, но вероятно у них могли быть мягкие констрейнты на другие элементы (ratio постера, например). Были и такие, где студенты немного отошли от жесткого следования макетам в дизайне, как предложила вам я.

Текстовые элементы обычно тяжело подаются макетированию, особенно если текст может динамически меняться, и для случая с центральным текстом уместно оставлять больше пространства, чем на фрейме в фирме. 

Я предложила вам вариант как исправить текущее решение, потому что его попробовала при ревью. Однако вы могли пойти и каким-нибудь другим путем. Например, начать верстать этот элемент сначала. В начале своей карьеры мне часто приходилось переделывать с нуля, потому что где-то допустила ошибку в проектировании. 

В любом случае, главное достичь корректности отображения, а не копированию значений с макетов. И это у вас получилось 👍

<img width="523" alt="Screenshot 2022-10-25 at 12 20 09" src="https://user-images.githubusercontent.com/20269264/197721595-19f440c5-ebbf-4342-8351-b8c29b834b81.png">

2022-10-25 08:40 UTC, ABashkirova commented
@vagamagajaga у меня все еще крашится на цветах

Вот текущая ветка, где лежат цвета: 
https://github.com/vagamagajaga/MovieQuiz-ios/tree/sprint_4/MovieQuiz/Resources/Assets.xcassets/Colors 

у вас получилось закомитеть цвета с переименованным названием, но предыдущие еще остались и именно их видит Xcode. 

Предлагаю зайти в директорию на вашем компьютере, удалить их и закомитеть изменения. 
```
$ git rm <file>
$ git commit -m "Deleted the file from the git repository"
$ git push
```

Дополнительно проверить, склонировав проект в отдельную директорию и запустив его (чтобы смогли посмотреть на ошибку, которую вижу я) 

<img width="1912" alt="Screenshot 2022-10-25 at 12 39 53" src="https://user-images.githubusercontent.com/20269264/197726255-6589ecdf-2a0f-4eac-8748-b7265ca86b3a.png">

2022-10-25 09:25 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +    @IBOutlet weak var movieCount: UILabel!
@vagamagajaga спасибо большое, что уделили этому моменту больше внимания. 

Перечитала последнюю редакцию урока и поняла, что из-за пропущенного в уроке нижнего констрейнта, можно сверстать 1к1 контейнер с лейблом. 

Похоже на ошибку в учебнике и мы ее поправим 🤓 прошу прощения)

2022-10-26 17:12 UTC, ABashkirova approved these changes
Отличная работа!

2022-10-27 16:05 UTC, vagamagajaga commented
@ABashkirova нужно ли сделать merge ветки sprint_4  в основную ветку?

2022-10-27 16:34 UTC, merged

2022-10-27 19:07 UTC, ABashkirova commented
@vagamagajaga все верно сделали :)