Sprint 06
vagamagajaga/MovieQuiz-ios pull request #4
Opened 2022-11-30 19:15 UTC by vagamagajaga

Подключена работа с сетью.
Отработка ошибок.

2022-11-30 21:37 UTC, ABashkirova requested changes
Код не запускается

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Обращу внимание на свойство `errorMessage`. 

Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов `items`. С пустым списком приложение будет выглядеть сломанным. Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.
С точки зрения проектирования API сервиса IMDB, эту ошибку лучше вернуть c кодом ошибки клиента ([группа 4хх](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#client_error_responses)). Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).

 **Примеры состояний, когда такое происходит:**

- API key неверный
- API key просрочен
- количество запросов в день превышено (по документации не больше 100)

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
Рекомендую, использовать свойство [hidesWhenStopped](https://developer.apple.com/documentation/uikit/uiactivityindicatorview/1622837-hideswhenstopped) у activityIndicator вместо ручного управления isHidden. Эту настройку можно сделать один раз во viewDidLoad или на сториборде.

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
кажется этот код должен быть вне тела этой функции.

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showLoadingIndicator()
Здесь не сильно играет роль, но принято делать в обратном порядке, чтобы избежать состояния гонки: сначала крутишь индикатор, потом отправляешь запрос на загрузку

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Servises/MoviesLoader.swift
> +
```suggestion

```

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Servises/QuestionFactory.swift
> +                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера. Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.

В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно. Это состояние стоит обработать, например, с помощью алерта. Не забудьте, что алерт будет обновлять UI и это тоже нужно учесть, ровно также, как и прерывание функции.

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Servises/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Пропущенное ослабление ссылки здесь - потенциально ошибка в будущем, конкретно в этом варианте не приводит к проблемам, но здесь неявно может захватывать сильный контекст внутри loadMovies. Рекомендую вообще всегда ослаблять ссылку, если не очень понятно надо/не надо -- дешевле же будет :)
```suggestion
        moviesLoader.loadMovies { [weak self] result in
```

2022-11-30 21:37 UTC, ABashkirova commented on MovieQuiz/Presentation/AlertPresenter.swift
> +    // MARK: - Variables
👍🏻

2022-12-01 06:43 UTC, vagamagajaga commented
> Код не запускается

Я не комимтил вот этот файл MovieQuiz.xcodeproj/project.pbxproj , потому что где-то услышал, что его не трогают, в этом может быть проблема?

2022-12-01 06:49 UTC, vagamagajaga commented on MovieQuiz/Servises/MoviesLoader.swift
> +
изменил

2022-12-01 06:51 UTC, vagamagajaga commented on MovieQuiz/Servises/QuestionFactory.swift
> +                print("Failed to load image")
То есть в catch стоит добавить код, который передаст в хэндлер ошибку, верно понимаю?

2022-12-01 09:10 UTC, vagamagajaga commented on MovieQuiz/Servises/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Этот код из курса, я так понял мы перенесли ссылку на строчку 21, разве нет?
19     func loadData() {
20        moviesLoader.loadMovies { result in
21           DispatchQueue.main.async { [weak self] in
22                guard let self = self else { return }

2022-12-01 10:02 UTC, vagamagajaga commented on MovieQuiz/Models/MostPopularMovies.swift
> +    let errorMessage: String
Исправил это в MovieLoader, добавил вывод сообщения с номером ошибки.
![image](https://user-images.githubusercontent.com/114681612/205024162-674b4f73-7a8f-4eb7-abb2-e290e150a9d2.png)

2022-12-01 10:25 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
Сначала не хотел париться, но в итоге хватило нажать одну кнопку в сториборде, и удалил эти строчки с индикатором, теперь еще индикатор включается перед показом результата. Не знаю, насколько это допустимо.

2022-12-01 10:26 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Эта функция дана из курса, тоже не вижу в ней необходимости, оставил тело без функции.

2022-12-01 10:27 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showLoadingIndicator()
Убрал эту функцию, пользуюсь твоим советом с hidesWhenStopped

2022-12-01 10:30 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showLoadingIndicator()
Изменил

2022-12-01 10:38 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Понял, убрал строку 134, но у меня вместо прогрузки индикатора, просто тормозит старая картинка. Посоветуешь, как исправить?

2022-12-01 11:46 UTC, vagamagajaga commented on MovieQuiz/Servises/QuestionFactory.swift
> +                print("Failed to load image")
Если я правильно понял, return в теле catch не поможет, и ты предлагаешь вызвать алерт с ошибкой. В таком случае мне нужно через инъекцию знакомить алертпрезентер с нетворкклиентом, верно?
Вообще странно, потому что этот код тоже дан курсом

2022-12-01 11:49 UTC, vagamagajaga commented
Саша, приветЗадал пару вопросов и прокомментировал твои комментарии, посмотри по возможности.Спасибо) 01.12.2022, 04:38, "Alexandra Bashkirova" ***@***.***>***@***.*** requested changes on this pull request.Код не запускаетсяIn MovieQuiz/Models/MostPopularMovies.swift:> @@ -0,0 +1,34 @@
+//
+//  MostPopularMovie.swift
+//  MovieQuiz
+//
+//  Created by Vagan Galstian on 26.11.2022.
+//
+
+import Foundation
+
+struct MostPopularMovies: Decodable {
+    let errorMessage: String
Обращу внимание на свойство errorMessage.Здесь может прийти текст с ошибкой, в таком случае сервис обычно возвращает пустой список фильмов items. С пустым списком приложение будет выглядеть сломанным. Это состояние называют краевым случаем, его стоит обрабатывать как ошибку, например, показывать алерт.С точки зрения проектирования API сервиса IMDB, эту ошибку лучше вернуть c кодом ошибки клиента (группа 4хх). Но случается и так, что ответ имеет статус код 200, а тело ответа содержит сообщение об ошибке, как в нашем примере. Такой ответ в любом случае необходимо обработать разработчику фронтенда (web, iOS, android).Примеры состояний, когда такое происходит:API key неверныйAPI key просроченколичество запросов в день превышено (по документации не больше 100)In MovieQuiz/Presentation/MovieQuizViewController.swift:> @@ -31,6 +31,25 @@ final class MovieQuizViewController: UIViewController, QuestionFactoryDelegate {
     }
     
     // MARK: - Methods
+    private func showLoadingIndicator() {
+        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
Рекомендую, использовать свойство hidesWhenStopped у activityIndicator вместо ручного управления isHidden. Эту настройку можно сделать один раз во viewDidLoad или на сториборде.In MovieQuiz/Presentation/MovieQuizViewController.swift:> +        func hideLoadingIndicator() {
+            activityIndicator.isHidden = true
+        }
кажется этот код должен быть вне тела этой функции.In MovieQuiz/Presentation/MovieQuizViewController.swift:> +        questionFactory?.loadData()
+        showLoadingIndicator()
Здесь не сильно играет роль, но принято делать в обратном порядке, чтобы избежать состояния гонки: сначала крутишь индикатор, потом отправляешь запрос на загрузкуIn MovieQuiz/Presentation/MovieQuizViewController.swift:> @@ -109,4 +128,15 @@ final class MovieQuizViewController: UIViewController, QuestionFactoryDelegate {
             self.showQuestion(quiz: (self.convert(model: currentQuestion)))
         }
     }
+    
+    // MARK: - Movieloader
+    func didLoadDataFromServer() {
+        activityIndicator.isHidden = true
+        questionFactory?.requestNextQuestion()
Ты можешь дополнительно показывать activityIndicator между загрузкой вопросов, потому что после загрузки фильмов, загрузка постера тоже занимает некоторое время из-за получения изображения.In MovieQuiz/Servises/MoviesLoader.swift:> +
+
+
⬇️ Suggested change-
-
-
In MovieQuiz/Servises/QuestionFactory.swift:>      }
     
+    func requestNextQuestion() {
+        DispatchQueue.global().async { [weak self] in
+            guard let self = self else { return }
+            let index = (0..<self.movies.count).randomElement() ?? 0
+            
+            guard let movie = self.movies[safe: index] else { return }
+            
+            var imageData = Data()
+            
+            do {
+                imageData = try Data(contentsOf: movie.resizedImageURL)
+            } catch {
+                print("Failed to load image")
Обращу внимание, что игра состоит из вопроса о рейтинге, на который отвечает пользователь, и контекста о фильме в виде постера. Без постера, пользователю будет затруднительно ответить на вопрос о рейтинге фильма верно.В этом месте, функция не завершает свою работу и идет формировать вопрос без постера. В таком случае, бизнес-логика приложения будет нарушена, потому что пользователь не сможет ответить корректно. Это состояние стоит обработать, например, с помощью алерта. Не забудьте, что алерт будет обновлять UI и это тоже нужно учесть, ровно также, как и прерывание функции.In MovieQuiz/Servises/QuestionFactory.swift:>      }
     
     //MARK: - Methods
-    func requestNextQuestion() {
-        
-        guard let index = (0..<questions.count).randomElement() else {  // 2
-            delegate?.didRecieveNextQuestion(question: nil)
-            return
+    func loadData() {
+        moviesLoader.loadMovies { result in
Пропущенное ослабление ссылки здесь - потенциально ошибка в будущем, конкретно в этом варианте не приводит к проблемам, но здесь неявно может захватывать сильный контекст внутри loadMovies. Рекомендую вообще всегда ослаблять ссылку, если не очень понятно надо/не надо -- дешевле же будет :) ⬇️ Suggested change-        moviesLoader.loadMovies { result in
+        moviesLoader.loadMovies { [weak self] result in
In MovieQuiz/Presentation/AlertPresenter.swift:> @@ -9,13 +9,14 @@ import Foundation
 import UIKit
 
 final class AlertPresenter: AlertPresenterProtocol {
-    
+    // MARK: - Variables
👍🏻—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

2022-12-01 12:24 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Пока не сообразил, как реализовать

2022-12-01 18:34 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
> теперь еще индикатор включается перед показом результата.

не понимаю в чем проблема

2022-12-01 18:35 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
все так, предлагают добавить. но разве ее предлагают добавлять внутрь другой функции? Можно референс?

2022-12-01 18:36 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
Простой алгоритм:
 сначала запускаешь индикатор,
потом запускаешь долгий и тяжелый запрос, 
на получение ответа с этого запроса – выключаешь индикатор

2022-12-01 18:37 UTC, ABashkirova commented on MovieQuiz/Servises/QuestionFactory.swift
> +                print("Failed to load image")
это рекомендация, здесь ты можешь подумать как улучшить свой проект

Задание не требует исправления этого участка 

Дружить алертпрезентер с нетворкклиентом не нужно, в этом классе уже есть пример как обрабатывать ошибки

2022-12-01 18:42 UTC, ABashkirova commented on MovieQuiz/Servises/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Это нелегкая тема, соглашусь. В учебнике мог остаться и такой вариант, это тоже корректно. 

Я же предлагаю задуматься о том как используются списки захвата, ослабляющие self. 
Еще раз скажу что: это **потенциальное** место ошибки, а не ошибка, в таком коде стоит быть внимательным и несколько раз перепроверить что weak self не нужен. 

Если комплишен функции loadMovies сервис moviesLoader захочет например сильно его сохранить, то внутрь замыкания будет захвачена сильная ссылка на фабрику. Это может приводить к утечкам памяти. Здесь же мы как разработчики этого кода гарантируем, что moviesLoader такого делать не будет, поэтому и ошибки не возникнет. Но если подходить к работке как пользователи сервиса moviesLoader, то лучше думать как "я не знаю как внутри сервис устроен", поэтому захвачу контекст слабо. 

Я предлагаю использовать более безопасный подход к проектированию кода :)

2022-12-01 18:45 UTC, ABashkirova commented
ой-ей, сверху какая-то лапша из моих комментов :)  я не знаю как на нее отвечать, прости!

Сори, я не могу обеспечивать здесь постоянный доступ. Лучше присылать исправленную работу на платформу, чтобы я ее гарантировано увидела. 
Проверь что код запускается так: скачай репозиторий с гитхаба, запусти как новое приложение. Если всего достаточно для запуска – я тоже смогу запустить, иначе - просто увидишь ошибки. 

Не стесняйся просить помощи у Наставника!

2022-12-02 12:52 UTC, vagamagajaga commented on MovieQuiz/Servises/QuestionFactory.swift
> +        moviesLoader.loadMovies { result in
Кажется понял, исправил

2022-12-02 12:52 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        showLoadingIndicator()
тоже из урока оказалось 
![image](https://user-images.githubusercontent.com/114681612/205295629-eb35ac11-7658-4243-b1b6-f3ef68db95d0.png)

2022-12-02 12:54 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        }
Не смог найти, помню, что там был вызов этой функции без ее объявления тела, я сам дописал его

2022-12-02 12:55 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = false // говорим, что индикатор загрузки не скрыт
нет проблема)

2022-12-02 13:08 UTC, vagamagajaga commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        questionFactory?.requestNextQuestion()
К сожалению, так и не вышло, сдам работу без этого апдейта. Буду признателен, если в ответ на следующее ревью укажешь, как это сделать. Я понимаю, что прогрузка нового фильма занимает время и было бы классно пустить индикатор поверх использованного фильма, но не получается

2022-12-03 09:38 UTC, ABashkirova commented on MovieQuiz/Servises/MoviesLoader.swift
> +                    handler(.failure(MoviesLoaderError.loadError(message: decodedMovies.errorMessage)))
👍🏻

2022-12-03 09:42 UTC, ABashkirova approved these changes

2022-12-03 09:42 UTC, ABashkirova commented on MovieQuiz/Servises/QuestionFactory.swift
> +                }
conrol +i

2022-12-03 09:42 UTC, ABashkirova commented on MovieQuiz/Servises/QuestionFactory.swift
> +                self.delegate?.didRecieveNextQuestion(question: question)
Рекоменду включить проверку правописания, чтобы не тащить в проект [очепятки](https://sarunw.com/posts/spell-checking-in-xcode/))

2022-12-03 09:42 UTC, ABashkirova commented on MovieQuiz/Presentation/MovieQuizViewController.swift
> +        activityIndicator.isHidden = true
для симметричности с showLoadingIndicator, я бы написала еще функцию hideLoadingIndicator

2022-12-04 09:26 UTC, merged